### ISSUE TITLE
Create an action in the plugin architecture to trigger the creation of a test sample button

### ISSUE THREAD

**Issue by mikeprecious** [mwhite05/Button-Symbols#1]
Hi @mwhite05 thanks for your work on this plugin! Looks promising! 

Wondering, rather than carrying around a Sketch file with a symbol button instance, wondering if you could bake in a triggered command as part of the plugin, to create a instance of the button symbol? Or perhaps convert an existing button element or button symbol into the format you've spec'd.

**Comment by mwhite05** [comment]
Hi @mikeprecious,

Glad you like it so far.

Bundling a pre-fab symbol into the plugin is actually something at the top of my [Future Plans list](https://github.com/mwhite05/Button-Symbols#user-content-future-plans).

I built this for use by just a couple of team members where I work so I didn't put forth the effort but it looks like this could be gaining some traction in the Sketch community. I already looked into how to make that work and it seems simple enough assuming the Sketch API documentation is up to date and complete on the subject.

**Comment by mwhite05** [comment]
@mikeprecious

so.... after much $*#(@*!** in regards to the lack of "real documentation" on the API I have a working (but mostly untested) alpha of this feature. I found a couple extras I want to work in to make it public-release ready but this build seems relatively stable so you can [check it out here](https://github.com/mwhite05/Button-Symbols/releases/tag/1.2.4-alpha.1) if you want.

To insert an instance of a working button symbol with all the correctly configured layers just use the shortcut: ctrl + shift + j

In this alpha the button will always be placed at `0,0` which I think is always relative to the artboard regardless of the group selected. I will adjust this to place the button more intelligently soon but I have to figure out what options are viable before I choose a path.

It will ensure there is a symbol named `Button` in your Symbols page and then create an instance of that symbol in the selected artboard/group.

If you have a layer selected that is not a group or artboard then it will find the parent group/artboard for that layer with one exception being if you have selected a text layer.

Not yet implemented but I'm thinking text layers will receive special handling of being converted into a button instance in their current location. The text value will be read and then the text layer will be replaced by a button instance with an override applied to set the label to the value of the original text layer. Thoughts?

**Comment by mwhite05** [comment]
I just released this officially in 1.3.0. If you have enhancement requests for the feature just post new issues for them.
