### ISSUE TITLE
Set different horizontal paddings (left & right)

### ISSUE THREAD

**Issue by anudeepgupta** [mwhite05/Button-Symbols#3]
Possible to add support for different paddings like you provided in positioning?
This will help support icon buttons where icons don't change their position on button resizing with cmd+J.

Also, it will be great if the positioning value could do simple arithmetics just like sketch does. That way it will become easier to reposition directly instead of moving the instances first and then updating the corresponding position values in the position attributes.

**Comment by anudeepgupta** [comment]
Turns out, the different padding feature is already supported but not documented perhaps. Was able to achieve by using parenthesis ex. (44,12) instead of simple 44,12

Just simple arithmetics in positioning attributes would be wonderful now. It'll be perfect.

**Comment by mwhite05** [comment]
Hi @anudeepgupta,

I'm glad you are finding this plugin useful!

I am actually working on some more advanced icon support that will allow icons and text to be inside the button symbol at the same time. Along with this I am building in support for different horizontal / vertical padding. I have been very busy for a while but will probably have time to get back on this soon.

In regards to the parenthetical syntax (44,12) I'm not sure if that's working... more likely it would just break the value parsing I'm doing and therefore might cause my plugin not to change the padding values. I will release official support for this feature as soon as I can though so don't worry, it is coming!


- Michael

**Comment by anudeepgupta** [comment]
Well IT IS working. You should try it. And if the support is not
intentional then this is quite amusing! It might be that sketch API
accidentally took care of this input method

**Comment by mwhite05** [comment]
@anudeepgupta 

I think what you were seeing might have been at least partly related to the resize anchoring and alignment of the label layer inside your button symbol master.

I ran some experimentation and determined that I cannot directly support variations on the left/right padding defined via the overrides (see below). However, if you upgrade to version 1.4.0 and check out the Advanced Button System.sketch file you can see some very powerful ways to include things like icons within your button symbols which (in my experience at least) is one of the primary reasons to have different left/right padding values.

I'm closing this ticket as something that is not directly possible at this time (and there is a workaround using the robust resize anchoring for the label layer). Given the way the plugin is designed to work off of the symbol master as a template, any movement of the label layer actually moves the symbol master's label layer which in turn changes the position of all labels in all instances of that symbol.
